### ISSUE TITLE
打開彈窗固定住後方的 body

### ISSUE THREAD

**Issue by CindyLyu** [CindyLyu/bug-records#5]
- 需求：打開彈窗並滾動時，不要滾動到後面的 body
- 解決方式：當打開彈窗時設定 body 的 css 為
```css
body.open-popup {
  overflow: hidden;
  position: fixed; /*  如果沒加此行在 safari ios 上還是能夠滾動到 body */
}
```
- 參考來源：
1. [Prevent Scroll Chaining With Overscroll Behavior](https://ishadeed.com/article/prevent-scroll-chaining-overscroll-behavior/)
